// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Server.proto

package game.world.protobuf;

public final class ServerPro {
  private ServerPro() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ServerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 area = 1;
    /**
     * <code>required int32 area = 1;</code>
     *
     * <pre>
     *大区
     * </pre>
     */
    boolean hasArea();
    /**
     * <code>required int32 area = 1;</code>
     *
     * <pre>
     *大区
     * </pre>
     */
    int getArea();

    // optional int32 probability = 2 [default = 100];
    /**
     * <code>optional int32 probability = 2 [default = 100];</code>
     *
     * <pre>
     *概率
     * </pre>
     */
    boolean hasProbability();
    /**
     * <code>optional int32 probability = 2 [default = 100];</code>
     *
     * <pre>
     *概率
     * </pre>
     */
    int getProbability();

    // required string ip = 3;
    /**
     * <code>required string ip = 3;</code>
     *
     * <pre>
     *IP
     * </pre>
     */
    boolean hasIp();
    /**
     * <code>required string ip = 3;</code>
     *
     * <pre>
     *IP
     * </pre>
     */
    java.lang.String getIp();
    /**
     * <code>required string ip = 3;</code>
     *
     * <pre>
     *IP
     * </pre>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    // required int32 port = 4;
    /**
     * <code>required int32 port = 4;</code>
     *
     * <pre>
     *端口
     * </pre>
     */
    boolean hasPort();
    /**
     * <code>required int32 port = 4;</code>
     *
     * <pre>
     *端口
     * </pre>
     */
    int getPort();

    // optional string name = 5;
    /**
     * <code>optional string name = 5;</code>
     *
     * <pre>
     *名字
     * </pre>
     */
    boolean hasName();
    /**
     * <code>optional string name = 5;</code>
     *
     * <pre>
     *名字
     * </pre>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 5;</code>
     *
     * <pre>
     *名字
     * </pre>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional string version = 6;
    /**
     * <code>optional string version = 6;</code>
     *
     * <pre>
     *版本号(优先选择)
     * </pre>
     */
    boolean hasVersion();
    /**
     * <code>optional string version = 6;</code>
     *
     * <pre>
     *版本号(优先选择)
     * </pre>
     */
    java.lang.String getVersion();
    /**
     * <code>optional string version = 6;</code>
     *
     * <pre>
     *版本号(优先选择)
     * </pre>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    // optional int32 max = 7;
    /**
     * <code>optional int32 max = 7;</code>
     *
     * <pre>
     *最大在线人数
     * </pre>
     */
    boolean hasMax();
    /**
     * <code>optional int32 max = 7;</code>
     *
     * <pre>
     *最大在线人数
     * </pre>
     */
    int getMax();

    // optional int32 cur = 8;
    /**
     * <code>optional int32 cur = 8;</code>
     *
     * <pre>
     *当前在线人数
     * </pre>
     */
    boolean hasCur();
    /**
     * <code>optional int32 cur = 8;</code>
     *
     * <pre>
     *当前在线人数
     * </pre>
     */
    int getCur();

    // optional bool online = 9;
    /**
     * <code>optional bool online = 9;</code>
     *
     * <pre>
     *是否在线(与中心服连接)
     * </pre>
     */
    boolean hasOnline();
    /**
     * <code>optional bool online = 9;</code>
     *
     * <pre>
     *是否在线(与中心服连接)
     * </pre>
     */
    boolean getOnline();
  }
  /**
   * Protobuf type {@code Server}
   */
  public static final class Server extends
      com.google.protobuf.GeneratedMessage
      implements ServerOrBuilder {
    // Use Server.newBuilder() to construct.
    private Server(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Server(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Server defaultInstance;
    public static Server getDefaultInstance() {
      return defaultInstance;
    }

    public Server getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Server(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              area_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              probability_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              ip_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              port_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              name_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              version_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              max_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              cur_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              online_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.world.protobuf.ServerPro.internal_static_Server_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.world.protobuf.ServerPro.internal_static_Server_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.world.protobuf.ServerPro.Server.class, game.world.protobuf.ServerPro.Server.Builder.class);
    }

    public static com.google.protobuf.Parser<Server> PARSER =
        new com.google.protobuf.AbstractParser<Server>() {
      public Server parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Server(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Server> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 area = 1;
    public static final int AREA_FIELD_NUMBER = 1;
    private int area_;
    /**
     * <code>required int32 area = 1;</code>
     *
     * <pre>
     *大区
     * </pre>
     */
    public boolean hasArea() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 area = 1;</code>
     *
     * <pre>
     *大区
     * </pre>
     */
    public int getArea() {
      return area_;
    }

    // optional int32 probability = 2 [default = 100];
    public static final int PROBABILITY_FIELD_NUMBER = 2;
    private int probability_;
    /**
     * <code>optional int32 probability = 2 [default = 100];</code>
     *
     * <pre>
     *概率
     * </pre>
     */
    public boolean hasProbability() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 probability = 2 [default = 100];</code>
     *
     * <pre>
     *概率
     * </pre>
     */
    public int getProbability() {
      return probability_;
    }

    // required string ip = 3;
    public static final int IP_FIELD_NUMBER = 3;
    private java.lang.Object ip_;
    /**
     * <code>required string ip = 3;</code>
     *
     * <pre>
     *IP
     * </pre>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string ip = 3;</code>
     *
     * <pre>
     *IP
     * </pre>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ip = 3;</code>
     *
     * <pre>
     *IP
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 port = 4;
    public static final int PORT_FIELD_NUMBER = 4;
    private int port_;
    /**
     * <code>required int32 port = 4;</code>
     *
     * <pre>
     *端口
     * </pre>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 port = 4;</code>
     *
     * <pre>
     *端口
     * </pre>
     */
    public int getPort() {
      return port_;
    }

    // optional string name = 5;
    public static final int NAME_FIELD_NUMBER = 5;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 5;</code>
     *
     * <pre>
     *名字
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string name = 5;</code>
     *
     * <pre>
     *名字
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 5;</code>
     *
     * <pre>
     *名字
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string version = 6;
    public static final int VERSION_FIELD_NUMBER = 6;
    private java.lang.Object version_;
    /**
     * <code>optional string version = 6;</code>
     *
     * <pre>
     *版本号(优先选择)
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string version = 6;</code>
     *
     * <pre>
     *版本号(优先选择)
     * </pre>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          version_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string version = 6;</code>
     *
     * <pre>
     *版本号(优先选择)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 max = 7;
    public static final int MAX_FIELD_NUMBER = 7;
    private int max_;
    /**
     * <code>optional int32 max = 7;</code>
     *
     * <pre>
     *最大在线人数
     * </pre>
     */
    public boolean hasMax() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 max = 7;</code>
     *
     * <pre>
     *最大在线人数
     * </pre>
     */
    public int getMax() {
      return max_;
    }

    // optional int32 cur = 8;
    public static final int CUR_FIELD_NUMBER = 8;
    private int cur_;
    /**
     * <code>optional int32 cur = 8;</code>
     *
     * <pre>
     *当前在线人数
     * </pre>
     */
    public boolean hasCur() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 cur = 8;</code>
     *
     * <pre>
     *当前在线人数
     * </pre>
     */
    public int getCur() {
      return cur_;
    }

    // optional bool online = 9;
    public static final int ONLINE_FIELD_NUMBER = 9;
    private boolean online_;
    /**
     * <code>optional bool online = 9;</code>
     *
     * <pre>
     *是否在线(与中心服连接)
     * </pre>
     */
    public boolean hasOnline() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional bool online = 9;</code>
     *
     * <pre>
     *是否在线(与中心服连接)
     * </pre>
     */
    public boolean getOnline() {
      return online_;
    }

    private void initFields() {
      area_ = 0;
      probability_ = 100;
      ip_ = "";
      port_ = 0;
      name_ = "";
      version_ = "";
      max_ = 0;
      cur_ = 0;
      online_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasArea()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, area_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, probability_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getIpBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, port_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getVersionBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, max_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, cur_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBool(9, online_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, area_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, probability_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getIpBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, port_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getVersionBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, max_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, cur_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, online_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.world.protobuf.ServerPro.Server parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.world.protobuf.ServerPro.Server parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.world.protobuf.ServerPro.Server parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.world.protobuf.ServerPro.Server parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.world.protobuf.ServerPro.Server parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.world.protobuf.ServerPro.Server parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.world.protobuf.ServerPro.Server parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.world.protobuf.ServerPro.Server parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.world.protobuf.ServerPro.Server parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.world.protobuf.ServerPro.Server parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.world.protobuf.ServerPro.Server prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Server}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.world.protobuf.ServerPro.ServerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.world.protobuf.ServerPro.internal_static_Server_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.world.protobuf.ServerPro.internal_static_Server_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.world.protobuf.ServerPro.Server.class, game.world.protobuf.ServerPro.Server.Builder.class);
      }

      // Construct using game.world.protobuf.ServerPro.Server.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        area_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        probability_ = 100;
        bitField0_ = (bitField0_ & ~0x00000002);
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        version_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        max_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        cur_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        online_ = false;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.world.protobuf.ServerPro.internal_static_Server_descriptor;
      }

      public game.world.protobuf.ServerPro.Server getDefaultInstanceForType() {
        return game.world.protobuf.ServerPro.Server.getDefaultInstance();
      }

      public game.world.protobuf.ServerPro.Server build() {
        game.world.protobuf.ServerPro.Server result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.world.protobuf.ServerPro.Server buildPartial() {
        game.world.protobuf.ServerPro.Server result = new game.world.protobuf.ServerPro.Server(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.area_ = area_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.probability_ = probability_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.max_ = max_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.cur_ = cur_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.online_ = online_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.world.protobuf.ServerPro.Server) {
          return mergeFrom((game.world.protobuf.ServerPro.Server)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.world.protobuf.ServerPro.Server other) {
        if (other == game.world.protobuf.ServerPro.Server.getDefaultInstance()) return this;
        if (other.hasArea()) {
          setArea(other.getArea());
        }
        if (other.hasProbability()) {
          setProbability(other.getProbability());
        }
        if (other.hasIp()) {
          bitField0_ |= 0x00000004;
          ip_ = other.ip_;
          onChanged();
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000010;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasVersion()) {
          bitField0_ |= 0x00000020;
          version_ = other.version_;
          onChanged();
        }
        if (other.hasMax()) {
          setMax(other.getMax());
        }
        if (other.hasCur()) {
          setCur(other.getCur());
        }
        if (other.hasOnline()) {
          setOnline(other.getOnline());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasArea()) {
          
          return false;
        }
        if (!hasIp()) {
          
          return false;
        }
        if (!hasPort()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.world.protobuf.ServerPro.Server parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.world.protobuf.ServerPro.Server) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 area = 1;
      private int area_ ;
      /**
       * <code>required int32 area = 1;</code>
       *
       * <pre>
       *大区
       * </pre>
       */
      public boolean hasArea() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 area = 1;</code>
       *
       * <pre>
       *大区
       * </pre>
       */
      public int getArea() {
        return area_;
      }
      /**
       * <code>required int32 area = 1;</code>
       *
       * <pre>
       *大区
       * </pre>
       */
      public Builder setArea(int value) {
        bitField0_ |= 0x00000001;
        area_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 area = 1;</code>
       *
       * <pre>
       *大区
       * </pre>
       */
      public Builder clearArea() {
        bitField0_ = (bitField0_ & ~0x00000001);
        area_ = 0;
        onChanged();
        return this;
      }

      // optional int32 probability = 2 [default = 100];
      private int probability_ = 100;
      /**
       * <code>optional int32 probability = 2 [default = 100];</code>
       *
       * <pre>
       *概率
       * </pre>
       */
      public boolean hasProbability() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 probability = 2 [default = 100];</code>
       *
       * <pre>
       *概率
       * </pre>
       */
      public int getProbability() {
        return probability_;
      }
      /**
       * <code>optional int32 probability = 2 [default = 100];</code>
       *
       * <pre>
       *概率
       * </pre>
       */
      public Builder setProbability(int value) {
        bitField0_ |= 0x00000002;
        probability_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 probability = 2 [default = 100];</code>
       *
       * <pre>
       *概率
       * </pre>
       */
      public Builder clearProbability() {
        bitField0_ = (bitField0_ & ~0x00000002);
        probability_ = 100;
        onChanged();
        return this;
      }

      // required string ip = 3;
      private java.lang.Object ip_ = "";
      /**
       * <code>required string ip = 3;</code>
       *
       * <pre>
       *IP
       * </pre>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string ip = 3;</code>
       *
       * <pre>
       *IP
       * </pre>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ip = 3;</code>
       *
       * <pre>
       *IP
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ip = 3;</code>
       *
       * <pre>
       *IP
       * </pre>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ip = 3;</code>
       *
       * <pre>
       *IP
       * </pre>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>required string ip = 3;</code>
       *
       * <pre>
       *IP
       * </pre>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ip_ = value;
        onChanged();
        return this;
      }

      // required int32 port = 4;
      private int port_ ;
      /**
       * <code>required int32 port = 4;</code>
       *
       * <pre>
       *端口
       * </pre>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 port = 4;</code>
       *
       * <pre>
       *端口
       * </pre>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>required int32 port = 4;</code>
       *
       * <pre>
       *端口
       * </pre>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000008;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 port = 4;</code>
       *
       * <pre>
       *端口
       * </pre>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000008);
        port_ = 0;
        onChanged();
        return this;
      }

      // optional string name = 5;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 5;</code>
       *
       * <pre>
       *名字
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string name = 5;</code>
       *
       * <pre>
       *名字
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 5;</code>
       *
       * <pre>
       *名字
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 5;</code>
       *
       * <pre>
       *名字
       * </pre>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 5;</code>
       *
       * <pre>
       *名字
       * </pre>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 5;</code>
       *
       * <pre>
       *名字
       * </pre>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        name_ = value;
        onChanged();
        return this;
      }

      // optional string version = 6;
      private java.lang.Object version_ = "";
      /**
       * <code>optional string version = 6;</code>
       *
       * <pre>
       *版本号(优先选择)
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string version = 6;</code>
       *
       * <pre>
       *版本号(优先选择)
       * </pre>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string version = 6;</code>
       *
       * <pre>
       *版本号(优先选择)
       * </pre>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string version = 6;</code>
       *
       * <pre>
       *版本号(优先选择)
       * </pre>
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string version = 6;</code>
       *
       * <pre>
       *版本号(优先选择)
       * </pre>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000020);
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string version = 6;</code>
       *
       * <pre>
       *版本号(优先选择)
       * </pre>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        version_ = value;
        onChanged();
        return this;
      }

      // optional int32 max = 7;
      private int max_ ;
      /**
       * <code>optional int32 max = 7;</code>
       *
       * <pre>
       *最大在线人数
       * </pre>
       */
      public boolean hasMax() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 max = 7;</code>
       *
       * <pre>
       *最大在线人数
       * </pre>
       */
      public int getMax() {
        return max_;
      }
      /**
       * <code>optional int32 max = 7;</code>
       *
       * <pre>
       *最大在线人数
       * </pre>
       */
      public Builder setMax(int value) {
        bitField0_ |= 0x00000040;
        max_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 max = 7;</code>
       *
       * <pre>
       *最大在线人数
       * </pre>
       */
      public Builder clearMax() {
        bitField0_ = (bitField0_ & ~0x00000040);
        max_ = 0;
        onChanged();
        return this;
      }

      // optional int32 cur = 8;
      private int cur_ ;
      /**
       * <code>optional int32 cur = 8;</code>
       *
       * <pre>
       *当前在线人数
       * </pre>
       */
      public boolean hasCur() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 cur = 8;</code>
       *
       * <pre>
       *当前在线人数
       * </pre>
       */
      public int getCur() {
        return cur_;
      }
      /**
       * <code>optional int32 cur = 8;</code>
       *
       * <pre>
       *当前在线人数
       * </pre>
       */
      public Builder setCur(int value) {
        bitField0_ |= 0x00000080;
        cur_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cur = 8;</code>
       *
       * <pre>
       *当前在线人数
       * </pre>
       */
      public Builder clearCur() {
        bitField0_ = (bitField0_ & ~0x00000080);
        cur_ = 0;
        onChanged();
        return this;
      }

      // optional bool online = 9;
      private boolean online_ ;
      /**
       * <code>optional bool online = 9;</code>
       *
       * <pre>
       *是否在线(与中心服连接)
       * </pre>
       */
      public boolean hasOnline() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional bool online = 9;</code>
       *
       * <pre>
       *是否在线(与中心服连接)
       * </pre>
       */
      public boolean getOnline() {
        return online_;
      }
      /**
       * <code>optional bool online = 9;</code>
       *
       * <pre>
       *是否在线(与中心服连接)
       * </pre>
       */
      public Builder setOnline(boolean value) {
        bitField0_ |= 0x00000100;
        online_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool online = 9;</code>
       *
       * <pre>
       *是否在线(与中心服连接)
       * </pre>
       */
      public Builder clearOnline() {
        bitField0_ = (bitField0_ & ~0x00000100);
        online_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Server)
    }

    static {
      defaultInstance = new Server(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Server)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Server_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Server_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Server.proto\"\223\001\n\006Server\022\014\n\004area\030\001 \002(\005\022" +
      "\030\n\013probability\030\002 \001(\005:\003100\022\n\n\002ip\030\003 \002(\t\022\014\n" +
      "\004port\030\004 \002(\005\022\014\n\004name\030\005 \001(\t\022\017\n\007version\030\006 \001" +
      "(\t\022\013\n\003max\030\007 \001(\005\022\013\n\003cur\030\010 \001(\005\022\016\n\006online\030\t" +
      " \001(\010B\"\n\023game.world.protobufB\tServerProH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Server_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Server_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Server_descriptor,
              new java.lang.String[] { "Area", "Probability", "Ip", "Port", "Name", "Version", "Max", "Cur", "Online", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
